export {
  default as Textarea,
  TEXTAREA_COLORS,
  TEXTAREA_RADII,
  TEXTAREA_SIZES,
  TEXTAREA_VARIANTS,
  type TextareaColor,
  type TextareaColorProp,
  type TextareaProps,
  type TextareaRadius,
  type TextareaRadiusProp,
  type TextareaSize,
  type TextareaSizeProp,
  type TextareaVariant,
  type TextareaVariantProp,
} from "./textarea.svelte";
