name: "Setup Pnpm"
description: "Setup Pnpm and node"
runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        package_json_file: package.json
    - name: Setup Node
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version-file: .nvmrc
        cache: "pnpm"
        cache-dependency-path: pnpm-lock.yaml
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
